# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b26796fadbeb1b7ce1a6f4d8bf19537cf853624f93c36add6c1ea8c242f2cf5ae9aaa8cfe7e14757d00f620ac804ed4d8ce4bed5a834883e4c46da635ce679e

test:
  secret_key_base: 942ac2b544fb1503d175a83079d8d9116c2c818029956a8da4f487aa26769ae010fb4995204ea21ed909a25155eb9e25262a728a94d40a7665ff47ee6073e7ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
